#!/usr/bin/env python3
#
# Created on 2021-12-09 to count files by extension.
#
# Example use:
#     ./count-ext ~/Pictures/originals/
#
import os
import sys

def file_exts(path):
    counts = {}
    for root, dirs, files in os.walk(path):
        for file in files:
            base, ext = os.path.splitext(file)
            if ext in counts:
                counts[ext] += 1
            else:
                counts[ext] = 1
    for key in sorted(counts.keys()):
        print(f'{key}: {counts[key]}')

if (sys.argv[1]):
    file_exts(sys.argv[1])
